In [1]:
!pip install torch

Looking in indexes: https://mirrors.aliyun.com/pypi/simple/


##  cat

In [3]:
import torch  
A=torch.ones(3,3)
B=2*torch.ones(3,3)

In [4]:
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
B

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
C=torch.cat((A,B),0)

In [7]:
C

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [8]:
D=torch.cat((A,B),1)
D


tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])

# stack

In [10]:
A=torch.arange(0,4)
A

tensor([0, 1, 2, 3])

In [11]:
B=torch.arange(5,9)
B

tensor([5, 6, 7, 8])

In [12]:
C=torch.stack((A,B),0)
C

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])

In [13]:
D=torch.stack((A,B),1)
D

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])

## 切分操作

In [14]:
# Chunk
A=torch.tensor([1,2,3,4,5,6,7,8,9,10])
B = torch.chunk(A, 2, 0)
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [15]:
A=torch.ones(4,4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
B = torch.chunk(A, 2, 0)
B

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [17]:
# split
A=torch.rand(4,4)
A

tensor([[0.6338, 0.5422, 0.6483, 0.9628],
        [0.0427, 0.5781, 0.5659, 0.0278],
        [0.6519, 0.4606, 0.2304, 0.2385],
        [0.1015, 0.4277, 0.5853, 0.4152]])

In [18]:
B=torch.split(A, 2, 0)
B

(tensor([[0.6338, 0.5422, 0.6483, 0.9628],
         [0.0427, 0.5781, 0.5659, 0.0278]]),
 tensor([[0.6519, 0.4606, 0.2304, 0.2385],
         [0.1015, 0.4277, 0.5853, 0.4152]]))

In [19]:
C=torch.split(A, 3, 0)
C

(tensor([[0.6338, 0.5422, 0.6483, 0.9628],
         [0.0427, 0.5781, 0.5659, 0.0278],
         [0.6519, 0.4606, 0.2304, 0.2385]]),
 tensor([[0.1015, 0.4277, 0.5853, 0.4152]]))

In [ ]:
# unbind

In [20]:
A=torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [22]:
b=torch.unbind(A, 0)
b

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]))

## 索引

In [23]:
#index_select
A=torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [24]:
B=torch.index_select(A,0,torch.tensor([1,3]))
B

#维度 0 = 行
#从矩阵 A 里挑第 1 行和第 3 行（注意从 0 开始计数）

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [25]:
C=torch.index_select(A,1,torch.tensor([0,3]))
C

#维度 1 = 列
#从矩阵 A 里挑第 0 列和第 3 列

tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])

In [ ]:
#masked_select

In [26]:
A=torch.rand(5)
A

tensor([0.8456, 0.1143, 0.0675, 0.7460, 0.1701])

In [28]:
B=A>0.3
B

#新的 Tensor 其实就是一个掩码张量，它的每一位表示了一个判断条件是否成立的结果

tensor([ True, False, False,  True, False])

In [29]:
C=torch.masked_select(A, B)
C

tensor([0.8456, 0.7460])

In [ ]:
# 可简化为
C=torch.masked_select(A, A>0.3)
C