In [133]:
!pip install torch

Looking in indexes: https://mirrors.aliyun.com/pypi/simple/


In [134]:
import torch  
data = [1, 2, 3]

## 方法1：直接创建tensor
torch.tensor(data, dtype=None, device=None,requires_grad=False)

tensor([1, 2, 3])

In [135]:
import numpy as np
ndarry = np.array([[1, 2, 3],
                    [4, 5, 6]], dtype=np.float32)

## 方法2：从Numpy中创建
torch.from_numpy(ndarry)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [136]:
# 创建零矩阵 Tensor
size = (100, 100)
torch.zeros(*size, dtype=None)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [137]:
# 对角线都为1
torch.eye(100, 200, dtype=torch.float32)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [138]:
# 随机矩阵
size = (100, 100)
mean = 1
std = 1
low = 0
high = 3
torch.rand(size)
torch.randn(size)
torch.normal(mean, std, size)
torch.randint(low, high, size)

tensor([[1, 2, 1,  ..., 1, 0, 2],
        [2, 1, 1,  ..., 0, 1, 2],
        [1, 0, 0,  ..., 2, 2, 1],
        ...,
        [1, 0, 2,  ..., 0, 1, 1],
        [2, 1, 2,  ..., 1, 0, 1],
        [2, 0, 1,  ..., 0, 2, 0]])

# Tensor 的常用操作

## 获取形状

In [139]:
a=torch.zeros(2, 3, 5)
a.shape

torch.Size([2, 3, 5])

In [140]:
a.size()

torch.Size([2, 3, 5])

In [141]:
a.numel() # 使用 numel() 函数直接统计元素数量。

30

## 矩阵转秩 (维度转换）

In [142]:
x = torch.rand(2,3,5)
x.shape

torch.Size([2, 3, 5])

In [143]:
x = x.permute(2,1,0)
x.shape

## 解释
#permute 是 维度重排，它不会改变数据，只是换了维度的顺序。
#(2, 1, 0) 的意思是：
#新的第0维 = 原来的第2维
#新的第1维 = 原来的第1维
#新的第2维 = 原来的第0维

#原来 shape 是 [2, 3, 5]：
#维度0 = 2
#维度1 = 3
#维度2 = 5

#换位后：
#新维度0 ← 原维度2 → 5
#新维度1 ← 原维度1 → 3
#新维度2 ← 原维度0 → 2


torch.Size([5, 3, 2])

In [144]:
x.shape

torch.Size([5, 3, 2])

In [145]:
x = x.transpose(1,0)   # transpose，不同于 permute，它每次只能转换两个维度，或者说交换两个维度的数据
x.shape

torch.Size([3, 5, 2])

## 形状变换

In [146]:
x = torch.randn(4, 4)
x.shape

torch.Size([4, 4])

In [147]:
x = x.view(2,8)  #通过 view 函数，将其修改为[2, 8]形状的 Tensor
x.shape

torch.Size([2, 8])

In [148]:
x = x.reshape(4,4) #通过reshape函数，修改其为[4,4]形状的Tensor
x.shape

torch.Size([4, 4])

## 增减维度

In [149]:
##squeeze()

In [150]:
x = torch.rand(2,1,3)
x.shape

torch.Size([2, 1, 3])

In [151]:
y = x.squeeze(1)
y.shape

#squeeze(1) 的意思是：尝试压缩第 1 维
#因为第1维的长度 = 1，可以被移除
#所以 [2, 1, 3] → [2, 3]

torch.Size([2, 3])

In [152]:
z = y.squeeze(1)
z.shape

#现在 y.shape = [2, 3]，第1维的长度是 3，不等于 1
#所以 无法压缩，shape 不变
#结果还是 [2, 3]

torch.Size([2, 3])

总结：
squeeze = 把长度为1的维度去掉
如果指定的维度大小 ≠ 1，就不做任何事
这就是为什么第二次 squeeze(1) 没有效果。

In [153]:
## unsqueeze()

In [154]:
x = torch.rand(2,1,3)
y = x.unsqueeze(2)
y.shape


# unsqueeze(dim) 会在指定位置 插入一个新维度（大小=1）
# unsqueeze(2) 的意思是：在 第2维 插入一个新维度

torch.Size([2, 1, 1, 3])